### ISSUE TITLE
release: tag a new release / commit ?

### ISSUE THREAD

**Issue by fanquake** [miniupnp/libnatpmp#25]
The latest available tarball for libnatpmp on http://miniupnp.free.fr/files/ is this file: http://miniupnp.free.fr/files/download.php?file=libnatpmp-20150609.tar.gz. It would be great to get a new official tag / release as:

* The current tarball is now > 7 years old, and the source is missing bug fixes, as well as new features, like the recently merged [support for pkg-config](https://github.com/miniupnp/libnatpmp/pull/19).

* The current tarball is somewhat misleading / confusing. It's dated 09/06/2015, however it actually contains the source code for an earlier commit, https://github.com/miniupnp/libnatpmp/commit/f376ab72bc4de0b45f4e10c9b287b7ffe2a1fcd1 (11/4/2014). It's not really clear why this commit was used, when at the time the tarball was created (I assume 09/06/2015), the latest commit was this one: https://github.com/miniupnp/libnatpmp/commit/cf7f452d667658592e354c6ae6a0d539e367285c (04/03/2015).

Distros / packagers will look for official releases / sources, meaning that basically all are pointing to the 20150609 source, i.e https://repology.org/project/libnatpmp/versions, while carrying additional patches.

**Comment by jrmarino** [comment]
I second this request.  Repology is considering this a snapshot because it's not properly tagged or released.
Can you please at least tag the head of the repo with something that looks like a release tag?

**Comment by fanquake** [comment]
As of now, the latest tag is now http://miniupnp.free.fr/files/libnatpmp-20230423.tar.gz, so I'll close this.
